import { test, expect } from '@playwright/test';

test('Instituciones Educativas', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByPlaceholder('Nombre de usuario').click();
  await page.getByPlaceholder('Nombre de usuario').fill('0105599385');
  await page.locator('.ant-input-affix-wrapper').click();
  await page.getByPlaceholder('Contraseña').click();
  await page.getByPlaceholder('Contraseña').fill('asd');
  await page.getByRole('button', { name: 'Ingresar' }).click();
  await page.getByRole('menuitem', { name: 'user Pacientes' }).click();
  await page.getByRole('link', { name: 'Instituciones Educativas' }).click();
  await page.getByRole('button', { name: ' Nuevo' }).click();
  await page.getByLabel('Nombre de la Institución').click();
  await page.getByLabel('Nombre de la Institución').fill('Test Institución educativa');
  await page.getByLabel('Dirección').click();
  await page.getByLabel('Dirección').fill('Test Dirección');
  await page.getByLabel('Tipo de Institución').click();
  await page.getByTitle('Fiscomisional').locator('div').click();
  await page.getByRole('button', { name: 'OK' }).click();
  await expect(page.locator('body')).toContainText('Institución creada correctamente');
  await page.getByRole('button', { name: 'right' }).click();
  await expect(page.locator('tbody')).toContainText('Test Institución educativa');
  await expect(page.locator('tbody')).toContainText('Test Dirección');
  await expect(page.locator('tbody')).toContainText('Fiscomisional');
  await expect(page.locator('tbody')).toContainText('Fiscomisional');
  await page.getByRole('button', { name: ' Editar' }).nth(4).click();
  await page.getByLabel('Nombre de la Institución').click();
  await page.getByLabel('Nombre de la Institución').fill('Test Institución educativa 2');
  await page.getByLabel('Dirección').click();
  await page.getByLabel('Dirección').fill('Test Dirección 2');
  await page.getByLabel('Editar Institución').getByText('Fiscomisional').click();
  await page.getByText('Particular', { exact: true }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await expect(page.locator('body')).toContainText('Institución actualizada correctamente');
  await expect(page.locator('tbody')).toContainText('Test Institución educativa 2');
  await expect(page.locator('tbody')).toContainText('Test Dirección 2');
  await expect(page.locator('tbody')).toContainText('Privada');
  await expect(page.locator('tbody')).toContainText('Privada');
  await page.getByRole('button', { name: ' Eliminar' }).nth(4).click();
  await page.getByRole('button', { name: 'Si' }).click();
  await expect(page.locator('body')).toContainText('Institución eliminada correctamente');
});