import { test, expect } from '@playwright/test';

test('Pacientes', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByPlaceholder('Nombre de usuario').click();
  await page.getByPlaceholder('Nombre de usuario').fill('0105599385');
  await page.locator('.ant-input-affix-wrapper').click();
  await page.getByPlaceholder('Contraseña').click();
  await page.getByPlaceholder('Contraseña').fill('asd');
  await page.getByRole('button', { name: 'Ingresar' }).click();
  await page.getByRole('complementary').getByText('Pacientes').click();
  await page.getByRole('link', { name: 'Nuevo' }).click();
  await page.locator('input[name="fechaApertura"]').fill('2024-11-12');
  await page.getByLabel('¿Pertenece a proyecto?').check();
  await page.locator('input[name="proyecto"]').click();
  await page.locator('input[name="proyecto"]').fill('UDIPSAI');
  await page.locator('div').filter({ hasText: /^CUENCA$/ }).nth(4).click();
  await page.locator('input[name="nombresApellidos"]').click();
  await page.locator('input[name="nombresApellidos"]').fill('Test Paciente');
  await page.locator('input[name="cedula"]').click();
  await page.locator('input[name="cedula"]').fill('1111111111111');
  await page.locator('input[name="fechaNacimiento"]').fill('2024-08-01');
  await page.locator('input[name="edad"]').click();
  await page.locator('input[name="edad"]').fill('1');
  await page.locator('input[name="domicilio"]').click();
  await page.locator('input[name="domicilio"]').fill('Calle 1 y Avenida 2');
  await page.locator('input[name="ciudad"]').click();
  await page.locator('input[name="ciudad"]').fill('Cuenca');
  await page.locator('input[name="telefono"]').click();
  await page.locator('input[name="telefono"]').fill('0123456789');
  await page.locator('input[name="celular"]').click();
  await page.locator('input[name="celular"]').fill('0987654321');
  await page.locator('div').filter({ hasText: /^Discapacidad Presenta Discapacidad$/ }).locator('span').nth(1).click();
  await page.getByText('Sí').click();
  await expect(page.locator('form')).toContainText('Portador de Carnet');
  await page.getByLabel('Portador de Carnet').check();
  await expect(page.locator('form')).toContainText('Tipo de Discapacidad');
  await expect(page.locator('form')).toContainText('Detalle de la Discapacidad');
  await expect(page.locator('form')).toContainText('Porcentaje de Discapacidad');
  await page.locator('div:nth-child(3) > .ant-form-item > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector > .ant-select-selection-item').first().click();
  await page.getByTitle('Física').locator('div').click();
  await page.locator('input[name="detalleDiscapacidad"]').click();
  await page.locator('input[name="detalleDiscapacidad"]').fill('Brazo amputado');
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('30');
  await page.getByText('Institución Educativa A').click();
  await page.locator('#rc_select_2').press('Escape');
  await page.locator('div').filter({ hasText: /^Institución Educativa$/ }).click();
  await page.getByText('Matutina').click();
  await page.getByText('Matutina').nth(1).click();
  await page.locator('input[name="perteneceInclusion"]').click();
  await page.locator('input[name="perteneceInclusion"]').fill('No');
  await page.locator('input[name="anioEducacion"]').click();
  await page.locator('input[name="anioEducacion"]').fill('1');
  await page.locator('input[name="paralelo"]').click();
  await page.locator('input[name="paralelo"]').fill('A');
  await page.locator('textarea[name="motivoConsulta"]').click();
  await page.locator('textarea[name="motivoConsulta"]').fill('Motivo 1');
  await page.locator('textarea[name="observaciones"]').click();
  await page.locator('textarea[name="observaciones"]').fill('Observación');
  await page.getByRole('button', { name: 'Guardar' }).click();
  await expect(page.locator('body')).toContainText('Cédula o RUC inválido');
  await page.locator('input[name="cedula"]').click();
  await page.locator('input[name="cedula"]').fill('2222222222222');
  await page.getByRole('button', { name: 'Guardar' }).click();
  await expect(page.locator('body')).toContainText('Cédula o RUC inválido');
  await page.locator('input[name="cedula"]').click();
  await page.locator('input[name="cedula"]').fill('2222222222');
  await page.getByRole('button', { name: 'Guardar' }).click();
  await expect(page.getByRole('heading')).toContainText('Listado de Pacientes', { timeout: 500000 });
  await page.getByPlaceholder('Buscar').click();
  await page.getByPlaceholder('Buscar').fill('2222222222');
  await page.getByRole('button', { name: 'search' }).click();
  await expect(page.locator('tbody')).toContainText('Test Paciente');
  await expect(page.locator('tbody')).toContainText('2222222222');
  await expect(page.locator('tbody')).toContainText('0123456789');
  await expect(page.locator('tbody')).toContainText('CUENCA');
  await page.getByRole('button', { name: ' Modificar' }).first().click();
  await page.locator('input[name="cedula"]').click();
  await page.locator('input[name="nombresApellidos"]').click();
  await page.locator('input[name="nombresApellidos"]').fill('Test Paciente 2');
  await page.getByRole('button', { name: 'Editar' }).click();
  await expect(page.getByRole('main')).toContainText('Proyecto al que pertenece: UDIPSAI');
  await expect(page.getByRole('main')).toContainText('Nombres y Apellidos: Test Paciente 2');
  await expect(page.getByRole('main')).toContainText('Ciudad: Cuenca');
  await expect(page.getByRole('main')).toContainText('Cédula: 2222222222');
  await expect(page.getByRole('main')).toContainText('Domicilio: Calle 1 y Avenida 2');
  await expect(page.getByRole('main')).toContainText('Teléfono: 0123456789');
  await expect(page.getByRole('main')).toContainText('Celular: 0987654321');
  await expect(page.getByRole('main')).toContainText('Sede: CUENCA');
  await expect(page.getByRole('main')).toContainText('Motivo de Consulta: Motivo 1');
  await expect(page.getByRole('main')).toContainText('Observaciones: Observación');
  await expect(page.getByRole('main')).toContainText('Año que cursa: 1');
  await page.getByText('Institución Educativa: Institución Educativa A').click();
  await expect(page.getByRole('main')).toContainText('Paralelo: A');
  await expect(page.getByRole('main')).toContainText('Inclusión Educativa: No');
  await expect(page.getByRole('main')).toContainText('Presenta Discapacidad: si');
  await expect(page.getByRole('main')).toContainText('Portador de Carnet: Sí');
  await expect(page.getByRole('main')).toContainText('Porcentaje de Discapacidad: 30');
  await expect(page.getByRole('main')).toContainText('Detalle de la Discapacidad: Brazo amputado');
  await page.getByText('Ficha Única', { exact: true }).click();
  await page.click('text=Seguimientos');
  await page.getByRole('button', { name: ' Nuevo Seguimiento' }).click();
  await page.getByLabel('Observación').click();
  await page.getByLabel('Observación').fill('abc123');
  await page.getByRole('button', { name: 'OK' }).click();
  await expect(page.locator('tbody')).toContainText('abc123');
  await page.getByRole('button', { name: ' Editar' }).click();
});